### Root route
GET http://localhost:5000/

###

### Api route
GET http://localhost:5000/api/

###

### API auth routes
GET http://localhost:5000/api/auth/

###

### Login
POST http://localhost:5000/api/auth/signin/
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "password"
}

###

### Signup
POST http://localhost:5000/api/auth/signup/
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "userName": "ernestwambua",
    "email": "user@email.com",
    "phoneNumber": "+254773303396",
    "password": "password"
}