version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    
  api:
    image: ernestwambua/kaizen-api:latest
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo

secrets:
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt
    