version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kaizen
      MONGO_INITDB_ROOT_PASSWORD: mebuvxCBSAGScgWs
      MONGO_INITDB_DATABASE: kaizen-db
      MONGO_INITDB_USER: kaizen
      MONGO_INITDB_PWD: mebuvxCBSAGScgWs
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kaizen
      ME_CONFIG_MONGODB_ADMINPASSWORD: mebuvxCBSAGScgWs
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: kaizen-db
      ME_CONFIG_MONGODB_URL: mongodb://kaizen:mebuvxCBSAGScgWs@mongo:27017/kaizen-db?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: kaizen
      ME_CONFIG_BASICAUTH_PASSWORD: kaizen1234
    depends_on:
      - mongo

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 5000:5000
    environment:
      PORT: 5000
    depends_on:
      - mongo